### PR TITLE
Fixes #197 HandoverDocumentation file visualization

### LINKED ISSUE #197: [BUG] Visualization Plugin not working properly for HandoverDocumentation submodel
**Describe the bug**
No file preview available for visualization plugin within the handover documentation submodel
NoDigitalFileFound
Despite the pdf file being present in the AAS, it is accessible when brwosing to the DigitalFile01 entity (see 2nd screenshot below) 

**To Reproduce**
1. Download the following AAS: 
[1376426_DSBC-32-100-PPVA-N3_71e7561b-9646-421d-8864-e87320932b84.zip](https://github.com/user-attachments/files/16143617/1376426_DSBC-32-100-PPVA-N3_71e7561b-9646-421d-8864-e87320932b84.zip)
2. Rename extension to .aasx
2. Upload on Basyx-Setup
3. Browse to HandoverDocumentation submodel
4. Go to Document01?BedienungsanleitungDE in the Visualization tab

**Expected behavior**
Show the content of the Bedienungsanleitung PDF, similar to what is shown when browsing to the DigitalFile01 within the submodel (see: 
DigitalFilePreview
)

**BaSyx (please complete the following information):**
- BaSyx Version  v2.0 
- BaSyx SDK Java
- AAS Version  DotAAS V3

**Screenshots**
see inline

**Used Asset Administration files (.aasx/.json/.xml)**
see inline

**BaSyx configuration**
Downloaded minimal configuration from: http://basyx.org/#/
-> no discovery, no mongodb, no mqtt, no dashboard

**Desktop (please complete the following information):**
 - OS: Ubuntu 24 (virtual machine)
 - Browser firefox
 - Version 124.0.1

### PR DESCRIPTION
**Pull request by aaronzi**
# Fixes HandoverDocumentation file visualization not working

## Description of Changes

Extracting the PreviewFile and DigitalFile now works by SemanticId instead of the previous approach using the IdShort.

## Related Issue

Closes #197 

## BaSyx Configuration for Testing

See related issue

## AAS Files Used for Testing

See related issue

### CODE REVIEW

**Review by jannikf02 — APPROVED** [review]

File: aas-gui/Frontend/aas-web-gui/src/components/SubmodelPlugins/HandoverDocumentation.vue [hunk 1]
```diff
@@ -226,13 +226,9 @@ export default defineComponent({
             // prepare each DocumentVersion
             document.documentVersions.forEach((documentVersion: any) => {
                 // extract the DigitalFile
-                documentVersion.digitalFile = documentVersion.value.find((element: any) => {
-                    return element.idShort === "DigitalFile";
-                });
+                documentVersion.digitalFile = this.getElementBySemanticId("0173-1#02-ABI504", documentVersion);
```
Comment (seicke) [inline aas-gui/Frontend/aas-web-gui/src/components/SubmodelPlugins/HandoverDocumentation.vue:229]: Shouldn't it be 0173-1#02-ABI504#001 instead of 0173-1#02-ABI504 (without version identifier #001)?

File: aas-gui/Frontend/aas-web-gui/src/components/SubmodelPlugins/HandoverDocumentation.vue [hunk 2]
```diff
@@ -226,13 +226,9 @@ export default defineComponent({
...
                 // extract the PreviewFile
-                documentVersion.previewFile = documentVersion.value.find((element: any) => {
-                    return element.idShort === "PreviewFile";
-                });
+                documentVersion.previewFile = this.getElementBySemanticId("0173-1#02-ABI505", documentVersion);
```
Comment (seicke) [inline aas-gui/Frontend/aas-web-gui/src/components/SubmodelPlugins/HandoverDocumentation.vue:231]: Shouldn't it be 0173-1#02-ABI505#001 instead of 0173-1#02-ABI505 (without version identifier #001)?
